version: 2

sources:
  - name: raw # Este es el nuevo nombre (alias) para el dataset
    dataset: gz_raw_data # Este es el nombre real en BigQuery
    tables:
      - name: sales # Cómo lo llamarás en dbt
        identifier: raw_gz_sales # Nombre real de la tabla en BigQuery
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship